// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYiXEF0E3pn_kNKjNigAJMm1GNkAT3Yg',
    appId: '1:547591929381:web:e7f04c27c230eed79489cc',
    messagingSenderId: '547591929381',
    projectId: 'reserva-cae',
    authDomain: 'reserva-cae.firebaseapp.com',
    storageBucket: 'reserva-cae.appspot.com',
    measurementId: 'G-CWWBBFK482',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKse8jUdMPU2rh68D_In_ILd7-hKz-5tU',
    appId: '1:547591929381:android:bbcf0056f43e109b9489cc',
    messagingSenderId: '547591929381',
    projectId: 'reserva-cae',
    storageBucket: 'reserva-cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPDoAf5Fmwdx1X4USB6nK97hRe50Uv_s',
    appId: '1:547591929381:ios:c6293389edbc4f269489cc',
    messagingSenderId: '547591929381',
    projectId: 'reserva-cae',
    storageBucket: 'reserva-cae.appspot.com',
    iosClientId: '547591929381-3gh9aiki2ko6dq8huukj34nrdpehdgs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservaCae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPDoAf5Fmwdx1X4USB6nK97hRe50Uv_s',
    appId: '1:547591929381:ios:c6293389edbc4f269489cc',
    messagingSenderId: '547591929381',
    projectId: 'reserva-cae',
    storageBucket: 'reserva-cae.appspot.com',
    iosClientId: '547591929381-3gh9aiki2ko6dq8huukj34nrdpehdgs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservaCae',
  );
}
